name: C/C++ CI

on: [push]

jobs:
  build-ubuntu-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B cmake-build-debug
      - name: build
        run: cmake --build cmake-build-debug
      - name: test
        run: cd cmake-build-debug && ctest
  build-ubuntu-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B cmake-build-release
      - name: build
        run: cmake --build cmake-build-release
      - name: test
        run: cd cmake-build-release && ctest
      - name: package
        run: cmake --install cmake-build-release --prefix cmake-build-install
