name: C/C++ CI

on: [push]

jobs:
  build-ubuntu-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B cmake-build-debug
      - name: build
        run: cmake --build cmake-build-debug
      - name: test
        run: cd cmake-build-debug && ctest
  build-ubuntu-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B cmake-build-release
      - name: build
        run: cmake --build cmake-build-release
      - name: test
        run: cd cmake-build-release && ctest
      - name: package
        run: cmake --install cmake-build-release --prefix cmake-build-install
      - name: tarball # TODO probably branch name here?
        run: tar Jcvf xania-$GITHUB_RUN_ID.tar.xz --transform "s|^cmake-build-install|./xania-$GITHUB_RUN_ID|" cmake-build-install
      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: xania-${{ github.run_id }}.tar.xz
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: releases/xania-${{ github.run_id }}.tar.xz
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}